name: Test action

on: push
#  release:
 #   types: [published]

jobs:

  notify:
    runs-on: ubuntu-latest
    name: Workflow to test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Post notification
        uses: ./
        with:
          forum: 5
          thread: 902724
          client: "Mouseclick1#0000"
          password: ${{ secrets.FORUM_PASSWORD }}
